name: BuildAndRunTests

on:
  push:
    branches: 
    - "main"
    - "develop"
  pull_request:
    branches: 
    - "main"
    - "develop"
env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    
    
    - run: |
        git submodule update --init
        git lfs install
        git lfs pull

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -A x64 -B ${{github.workspace}}/build -D EDITOR=OFF -D ENABLE_TEST=TRUE

#     - name: Upload Artifacts(without build)
#       uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: Windows_x64_nobuild
#         path: ${{github.workspace}}/
        
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
#      working-directory: ${{github.workspace}}/build/Src/Runtime/Test/${{env.BUILD_TYPE}}
      #run: ctest -C ${{env.BUILD_TYPE}}
      run: |
        cd build/Src/Runtime/Test/${{env.BUILD_TYPE}}
        NativeRuntime_Test.exe
      shell: cmd
      
      
#     - name: Upload Artifacts
#       uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: Windows_x64
#         path: ${{github.workspace}}/
        

    # Post Discord Notify(by Actions Status Discord)
    - name: Actions Status Discord
      # uses: sarisia/actions-status-discord@f268209d088ace9f9666322b04d60e013fef212d
      uses: sarisia/actions-status-discord@v1.10.0
      if: always()
      env: 
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
